FROM golang:latest as build-container
WORKDIR /go/src/app
COPY .. .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o web .

FROM alpine:latest
WORKDIR /app
COPY --from=build-container /go/src/app/web .
EXPOSE 6000
CMD ["./web"]